package org.sert2521.rapidreact2022

const val TICKS_PER_ROTATION = 4096

const val WHEEL_SPINS_PER_MOTOR_SPIN = 0.0
const val WHEEL_CIRCUMFERENCE = 0.0
const val WHEEL_DISTANCE_PER_PULSE = WHEEL_CIRCUMFERENCE * (WHEEL_SPINS_PER_MOTOR_SPIN / TICKS_PER_ROTATION)

enum class Motors(val id: Int, val encoderDistancePerPulse: Double) {
    FRONT_LEFT(0, WHEEL_DISTANCE_PER_PULSE),
    BACK_LEFT(0, WHEEL_DISTANCE_PER_PULSE),
    FRONT_RIGHT(0, WHEEL_DISTANCE_PER_PULSE),
    BACK_RIGHT(0, WHEEL_DISTANCE_PER_PULSE)
}